name: 🐞 Bug Report
description: File a bug report
labels: ["untriaged"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🙏
        
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug 💬
      description: A clear and concise description of what the bug is. Thanks!
      placeholder: I am doing ... What I expect is ... What actually happening is ...
    validations:
      required: true
      
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a link for download or a link to a repo that can reproduce the problem you ran into. A [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) is required ([Why?](https://antfu.me/posts/why-reproductions-are-required)). If a report is vague (e.g. just a generic error message) and has no reproduction, it will receive a "need reproduction" label. For quickly collecting all the necessary files in Unity you can use the menu item under ``Needle Engine/Bug Report/Zip Scene`` 
      placeholder: Reproduction URL
    validations:
      required: true
      
  - type: dropdown
    id: OS
    attributes:
      label: Operating System
      description: Which operating system are you using?
      options:
        - Windows
        - OSX
        - Linux
    validations:
      required: true
      
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Mozilla XR
        
  - type: dropdown
    id: version
    attributes:
      label: Editor Version
      description: Which Unity Editor version are you using?
      options:
        - 2020.3
        - 2021.3
        - 2022.x
        - 2023.x
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce 🔢
      description: Please provide any reproduction steps that may need to be described. E.g. if it happens only when deploying to glitch or doing something specific in the editor or when making production or development builds make sure this is clear
      placeholder: Create a new minimal template, add _this_ script and start the server
    validations:
      required: true

  - type: textarea
    id: project-info
    attributes:
      label: Project Info (Unity only)
      description: |
        Optional if provided reproduction. Please try not to insert an image but copy paste the log text.
        1. Click the menu item ``Needle Engine/Bug Report/Copy Project Info``
        2. Paste the copied project info in the format below (this will automatically formatted - no need for backticks)
      render: json
       
     
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations 🩹
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Follow our [Code of Conduct](https://github.com/needle-tools/needle-engine-support/blob/main/CODE_OF_CONDUCT.md)
          required: true
        - label: Read the [docs](https://docs.needle.tools).
          required: true
        - label: Check that there isn't [already an issue](https://github.com/needle-tools/needle-engine-support/issues) that reports the same bug to avoid creating a duplicate.
          required: true
        - label: Make sure this is a Vite issue and not a Needle-Engine-specific issue. For example, if it's a Unity related bug, it should likely be reported to [Unity](https://unity3d.com/unity/qa/bug-reporting) instead.
          required: true
        - label: Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/needle-tools/needle-engine-support/discussions) or join our [Discord Chat Server](https://discord.needle.tools).
          required: true
        - label: The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
          required: false
